version: '3'
services:
  socat-docker:
    image: alpine/socat
    command: "tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins_jenkins
    restart: always
    ports:
      - "127.0.0.1:2376:2375"

networks:
  jenkins_jenkins:
